#!/usr/bin/python

import socket
import sys

UDP_IP="127.0.0.1"
UDP_PORT=5005

print "UDP target IP:", UDP_IP
print "UDP target port:", UDP_PORT

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

last = ""
while True:
    inp = raw_input()
    if inp != last:
        sock.sendto(inp, (UDP_IP, UDP_PORT))
    last = inp
