#!/usr/bin/python

import sys
import os

import pygame
import pygame.midi
from pygame.locals import *

from time import sleep

import socket
from select import select

UDP_IP="127.0.0.1"
UDP_PORT=5005

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))

if __name__ == '__main__':
    while True:
        print "Tick"
        try:
            while True:
                [r, w, x] = select([sock, ], [], [], 0)
                if r:
                    data, addr = sock.recvfrom( 1024 ) # buffer size is 1024 bytes
                    params = dict([e.split("=") for e in data.split(",")])
                    print params
                else:
                    break
        except Exception as e:
            print "Fail", e
        sleep(0.5)
