#!/usr/bin/python

import sys
import os

import pygame
import pygame.midi
from pygame.locals import *

from time import sleep


# network imports
import socket
from select import select

# network setup
UDP_IP="127.0.0.1"
UDP_PORT=5005
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))
last_known_state = None

# update state if there are updates, return state
def get_car_state():
    global last_known_state
    try:
        while True:
            [r, w, x] = select([sock, ], [], [], 0)
            if r:
                data, addr = sock.recvfrom(1024)
                last_known_state = dict([e.split("=") for e in data.split(",")])
            else:
                break
    except Exception as e:
        print "Fail at getting state", e
    return last_known_state


if __name__ == '__main__':
    while True:
        print "Tick"
        print get_car_state()
        sleep(0.5)
